version: "3.8"

services:

  configserver:
    image: danielgomesaf/configserver:latest
    mem_limit: 700mb
    ports:
      - "8071:8071"
    networks:
      - bank-network

  eurekaserver:
    image: danielgomesaf/eurekaserver:latest
    mem_limit: 700mb
    ports:
      - "8070:8070"
    networks:
      - bank-network
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/

  accounts:
    image: danielgomesaf/accounts:latest
    mem_limit: 700mb
    ports:
      - "8080:8080"
    networks:
      - bank-network
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/
  
  loans:
    image: danielgomesaf/loans:latest
    mem_limit: 700mb
    ports:
      - "8090:8090"
    networks:
      - bank-network
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/

  cards:
    image: danielgomesaf/cards:latest
    mem_limit: 700mb
    ports:
      - "9000:9000"
    networks:
      - bank-network
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/

networks:
  bank-network: