version: "3.8"

services:

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./../monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - bank-network

  grafana:
    image: "grafana/grafana:latest"
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN=admin
      - GF_SECURITY_ADMIN_PASSWORD=password
    networks:
      - bank-network
    depends_on:
      - prometheus

  zipkin:
    image: openzipkin/zipkin
    mem_limit: 700mb
    ports:
      - "9411:9411"
    networks:
      - bank-network

  configserver:
    image: danielgomesaf/configserver:latest
    mem_limit: 700mb
    ports:
      - "8071:8071"
    networks:
      - bank-network
    depends_on:
      - zipkin
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/
  
  eurekaserver:
    image: danielgomesaf/eurekaserver:latest
    mem_limit: 700mb
    ports:
      - "8070:8070"
    networks:
      - bank-network
    depends_on:
      - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/

  accounts:
    image: danielgomesaf/accounts:latest
    mem_limit: 700mb
    ports:
      - "8080:8080"
    networks:
      - bank-network
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/

  loans:
    image: danielgomesaf/loans:latest
    mem_limit: 700mb
    ports:
      - "8090:8090"
    networks:
      - bank-network
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/

  cards:
    image: danielgomesaf/cards:latest
    mem_limit: 700mb
    ports:
      - "9000:9000"
    networks:
      - bank-network
    depends_on:
      - configserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/

  gatewayserver:
    image: danielgomesaf/gatewayserver:latest
    mem_limit: 700mb
    ports:
      - "8072:8072"
    networks:
      - bank-network
    depends_on:
      - configserver
      - eurekaserver
      - accounts
      - cards
      - loans
    deploy:
      restart_policy:
        condition: on-failure
        delay: 45s
        max_attempts: 3
        window: 180s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8070/eureka/
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/

networks:
  bank-network: